// <auto-generated />
using System;
using Lemon.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lemon.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LemonContext))]
    [Migration("20181214101322_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lemon.Core.Entities.Artists.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Artist");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Artist");
                });

            modelBuilder.Entity("Lemon.Core.Entities.Artists.Band", b =>
                {
                    b.HasBaseType("Lemon.Core.Entities.Artists.Artist");

                    b.Property<int>("ActiveFromYear");

                    b.Property<int?>("ActiveToYear");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.ToTable("Band");

                    b.HasDiscriminator().HasValue("Band");
                });

            modelBuilder.Entity("Lemon.Core.Entities.Artists.Musician", b =>
                {
                    b.HasBaseType("Lemon.Core.Entities.Artists.Artist");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<DateTime?>("DateOfDeath");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.ToTable("Musician");

                    b.HasDiscriminator().HasValue("Musician");
                });
#pragma warning restore 612, 618
        }
    }
}
